#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  extra_joints:
    - name: 'finger_joint'
      position: 0.6

# eTaSl example controller
etasl_controller:
  type: "etasl_ros_controllers/EtaslController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  input:
    names:
      - "force_z"
      - "tgt_x"
      - "tgt_y"
      - "tgt_z"
      - "block_frame"
      - "peg1_frame"
      - "peg2_frame"
      - "peg3_frame"
      - "peg4_frame"
      - "peg5_frame"
    types:
      - "Scalar"
      - "Scalar"
      - "Scalar"
      - "Scalar"
      - "Frame"
      - "Frame"
      - "Frame"
      - "Frame"
      - "Frame"
      - "Frame"
  output:
    names:
      - "e_event"
    types:
      - "Event"
  task_specification: "$(find etasl_ros_control_examples)/scripts/example_peg_in_hole_multiple.lua"